# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11dcd5cde04252e5a383fcac10638b2d187b34b1f19d0ed07e8831ca4617a3b099c261fa0c0021290cfb968b98d38cca3e9a67e5acc520d8cbb6349102dd3f04

test:
  secret_key_base: abadb69a2187b3fe5e832824bd393b9da6af3fdb92f2eaf20cd2191c1fc80dc0b3d65f4992b85d8d4f5b14b0f804a98a4fad465efb416de1c4d0cb9c326495ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
